export {canUseDOM} from './canUseDOM';
export {generateGUID} from './generateGUID';
export {getAltColour} from './getAltColour';
export {getModifiers} from './getModifiers';
export {noop} from './noop';
export {generateChars, generateLorem, generateWords, Placeholder} from './Placeholder';
export {replaceTokens} from './replaceTokens';
export {sentenceCase} from './sentenceCase';
export {sleep} from './sleep';
export {slugify} from './slugify';
